/**
 * This class is generated by jOOQ
 */
package JooqORM;


import JooqORM.tables.ChineseMarketCompany;
import JooqORM.tables.UsmarketCompany;
import JooqORM.tables.records.ChineseMarketCompanyRecord;
import JooqORM.tables.records.UsmarketCompanyRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>StockMarket</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChineseMarketCompanyRecord> KEY_CHINESE_MARKET_COMPANY_PRIMARY = UniqueKeys0.KEY_CHINESE_MARKET_COMPANY_PRIMARY;
    public static final UniqueKey<UsmarketCompanyRecord> KEY_USMARKET_COMPANY_PRIMARY = UniqueKeys0.KEY_USMARKET_COMPANY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ChineseMarketCompanyRecord> KEY_CHINESE_MARKET_COMPANY_PRIMARY = createUniqueKey(ChineseMarketCompany.CHINESE_MARKET_COMPANY, "KEY_chinese_market_company_PRIMARY", ChineseMarketCompany.CHINESE_MARKET_COMPANY.STOCKID);
        public static final UniqueKey<UsmarketCompanyRecord> KEY_USMARKET_COMPANY_PRIMARY = createUniqueKey(UsmarketCompany.USMARKET_COMPANY, "KEY_usmarket_company_PRIMARY", UsmarketCompany.USMARKET_COMPANY.STOCKID);
    }
}
