/**
 * This class is generated by jOOQ
 */
package JooqORM;


import JooqORM.tables.ChineseMarketCompany;
import JooqORM.tables.Cmarketearning;
import JooqORM.tables.UsmarketCompany;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in StockMarket
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>StockMarket.chinese_market_company</code>.
     */
    public static final ChineseMarketCompany CHINESE_MARKET_COMPANY = JooqORM.tables.ChineseMarketCompany.CHINESE_MARKET_COMPANY;

    /**
     * The table <code>StockMarket.cmarketearning</code>.
     */
    public static final Cmarketearning CMARKETEARNING = JooqORM.tables.Cmarketearning.CMARKETEARNING;

    /**
     * The table <code>StockMarket.usmarket_company</code>.
     */
    public static final UsmarketCompany USMARKET_COMPANY = JooqORM.tables.UsmarketCompany.USMARKET_COMPANY;
}
