/**
 * This class is generated by jOOQ
 */
package JooqORM;


import JooqORM.tables.Company;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ChineseStock
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ChineseStock.company</code>.
     */
    public static final Company COMPANY = JooqORM.tables.Company.COMPANY;
}
