/**
 * This class is generated by jOOQ
 */
package JooqORM;


import JooqORM.tables.Chinesemarketcompany;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in StockMarket
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>StockMarket.ChineseMarketCompany</code>.
     */
    public static final Chinesemarketcompany CHINESEMARKETCOMPANY = JooqORM.tables.Chinesemarketcompany.CHINESEMARKETCOMPANY;
}
