/**
 * This class is generated by jOOQ
 */
package JooqORM.tables;


import JooqORM.Keys;
import JooqORM.Stockmarket;
import JooqORM.tables.records.ChinesemarketcompanyRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chinesemarketcompany extends TableImpl<ChinesemarketcompanyRecord> {

    private static final long serialVersionUID = 1712632413;

    /**
     * The reference instance of <code>StockMarket.ChineseMarketCompany</code>
     */
    public static final Chinesemarketcompany CHINESEMARKETCOMPANY = new Chinesemarketcompany();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChinesemarketcompanyRecord> getRecordType() {
        return ChinesemarketcompanyRecord.class;
    }

    /**
     * The column <code>StockMarket.ChineseMarketCompany.stockid</code>. 股票ID
     */
    public final TableField<ChinesemarketcompanyRecord, String> STOCKID = createField("stockid", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "股票ID");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.companyname</code>. 公司名称
     */
    public final TableField<ChinesemarketcompanyRecord, String> COMPANYNAME = createField("companyname", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "公司名称");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.currentprice</code>. Current stock price
     */
    public final TableField<ChinesemarketcompanyRecord, Double> CURRENTPRICE = createField("currentprice", org.jooq.impl.SQLDataType.DOUBLE, this, "Current stock price");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.currentpricetimestamp</code>.
     */
    public final TableField<ChinesemarketcompanyRecord, Timestamp> CURRENTPRICETIMESTAMP = createField("currentpricetimestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.openprice</code>. 开盘价
     */
    public final TableField<ChinesemarketcompanyRecord, Double> OPENPRICE = createField("openprice", org.jooq.impl.SQLDataType.DOUBLE, this, "开盘价");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.closeprice</code>. 昨日收盘价
     */
    public final TableField<ChinesemarketcompanyRecord, Double> CLOSEPRICE = createField("closeprice", org.jooq.impl.SQLDataType.DOUBLE, this, "昨日收盘价");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.highest_price</code>. 最高价
     */
    public final TableField<ChinesemarketcompanyRecord, Double> HIGHEST_PRICE = createField("highest_price", org.jooq.impl.SQLDataType.DOUBLE, this, "最高价");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.lowest_price</code>. 最低价
     */
    public final TableField<ChinesemarketcompanyRecord, Double> LOWEST_PRICE = createField("lowest_price", org.jooq.impl.SQLDataType.DOUBLE, this, "最低价");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.marketcap</code>. 总市值
     */
    public final TableField<ChinesemarketcompanyRecord, String> MARKETCAP = createField("marketcap", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "总市值");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.capitalizationvalue</code>. 流通市值
     */
    public final TableField<ChinesemarketcompanyRecord, String> CAPITALIZATIONVALUE = createField("capitalizationvalue", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "流通市值");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.tradingvolume</code>. 成交量
     */
    public final TableField<ChinesemarketcompanyRecord, String> TRADINGVOLUME = createField("tradingvolume", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "成交量");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.tradingvalue</code>. 成交额
     */
    public final TableField<ChinesemarketcompanyRecord, String> TRADINGVALUE = createField("tradingvalue", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "成交额");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.oscillation</code>. 股票振幅
     */
    public final TableField<ChinesemarketcompanyRecord, String> OSCILLATION = createField("oscillation", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "股票振幅");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.turnoverrate</code>. 换手率
     */
    public final TableField<ChinesemarketcompanyRecord, String> TURNOVERRATE = createField("turnoverrate", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "换手率");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.PBR</code>. 市净率 Price-to-book ratio
     */
    public final TableField<ChinesemarketcompanyRecord, Double> PBR = createField("PBR", org.jooq.impl.SQLDataType.DOUBLE.defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DOUBLE)), this, "市净率 Price-to-book ratio");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.PER</code>. 市盈率
     */
    public final TableField<ChinesemarketcompanyRecord, Double> PER = createField("PER", org.jooq.impl.SQLDataType.DOUBLE.defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DOUBLE)), this, "市盈率");

    /**
     * The column <code>StockMarket.ChineseMarketCompany.last_update_date_time</code>. 最后一次更新时间
     */
    public final TableField<ChinesemarketcompanyRecord, Timestamp> LAST_UPDATE_DATE_TIME = createField("last_update_date_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "最后一次更新时间");

    /**
     * Create a <code>StockMarket.ChineseMarketCompany</code> table reference
     */
    public Chinesemarketcompany() {
        this("ChineseMarketCompany", null);
    }

    /**
     * Create an aliased <code>StockMarket.ChineseMarketCompany</code> table reference
     */
    public Chinesemarketcompany(String alias) {
        this(alias, CHINESEMARKETCOMPANY);
    }

    private Chinesemarketcompany(String alias, Table<ChinesemarketcompanyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Chinesemarketcompany(String alias, Table<ChinesemarketcompanyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stockmarket.STOCKMARKET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ChinesemarketcompanyRecord> getPrimaryKey() {
        return Keys.KEY_CHINESEMARKETCOMPANY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ChinesemarketcompanyRecord>> getKeys() {
        return Arrays.<UniqueKey<ChinesemarketcompanyRecord>>asList(Keys.KEY_CHINESEMARKETCOMPANY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Chinesemarketcompany as(String alias) {
        return new Chinesemarketcompany(alias, this);
    }

    /**
     * Rename this table
     */
    public Chinesemarketcompany rename(String name) {
        return new Chinesemarketcompany(name, null);
    }
}
