/**
 * This class is generated by jOOQ
 */
package JooqORM.tables;


import JooqORM.Keys;
import JooqORM.Stockmarket;
import JooqORM.tables.records.CmarketearningRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cmarketearning extends TableImpl<CmarketearningRecord> {

    private static final long serialVersionUID = -1046494991;

    /**
     * The reference instance of <code>StockMarket.cmarketearning</code>
     */
    public static final Cmarketearning CMARKETEARNING = new Cmarketearning();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CmarketearningRecord> getRecordType() {
        return CmarketearningRecord.class;
    }

    /**
     * The column <code>StockMarket.cmarketearning.stockid</code>. 股票ID
     */
    public final TableField<CmarketearningRecord, String> STOCKID = createField("stockid", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "股票ID");

    /**
     * The column <code>StockMarket.cmarketearning.grossmargin</code>. 毛利率
     */
    public final TableField<CmarketearningRecord, Double> GROSSMARGIN = createField("grossmargin", org.jooq.impl.SQLDataType.DOUBLE, this, "毛利率");

    /**
     * The column <code>StockMarket.cmarketearning.reporturl</code>. 主要财务指标
     */
    public final TableField<CmarketearningRecord, String> REPORTURL = createField("reporturl", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "主要财务指标");

    /**
     * The column <code>StockMarket.cmarketearning.roe</code>. 净资产收益率
     */
    public final TableField<CmarketearningRecord, Double> ROE = createField("roe", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "净资产收益率");

    /**
     * Create a <code>StockMarket.cmarketearning</code> table reference
     */
    public Cmarketearning() {
        this("cmarketearning", null);
    }

    /**
     * Create an aliased <code>StockMarket.cmarketearning</code> table reference
     */
    public Cmarketearning(String alias) {
        this(alias, CMARKETEARNING);
    }

    private Cmarketearning(String alias, Table<CmarketearningRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cmarketearning(String alias, Table<CmarketearningRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stockmarket.STOCKMARKET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CmarketearningRecord> getPrimaryKey() {
        return Keys.KEY_CMARKETEARNING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CmarketearningRecord>> getKeys() {
        return Arrays.<UniqueKey<CmarketearningRecord>>asList(Keys.KEY_CMARKETEARNING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cmarketearning as(String alias) {
        return new Cmarketearning(alias, this);
    }

    /**
     * Rename this table
     */
    public Cmarketearning rename(String name) {
        return new Cmarketearning(name, null);
    }
}
