/**
 * This class is generated by jOOQ
 */
package JooqORM.tables;


import JooqORM.Keys;
import JooqORM.Stockmarket;
import JooqORM.tables.records.UsmarketcompanyRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usmarketcompany extends TableImpl<UsmarketcompanyRecord> {

    private static final long serialVersionUID = 986768707;

    /**
     * The reference instance of <code>StockMarket.USMarketCompany</code>
     */
    public static final Usmarketcompany USMARKETCOMPANY = new Usmarketcompany();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsmarketcompanyRecord> getRecordType() {
        return UsmarketcompanyRecord.class;
    }

    /**
     * The column <code>StockMarket.USMarketCompany.stockid</code>. 股票ID
     */
    public final TableField<UsmarketcompanyRecord, String> STOCKID = createField("stockid", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "股票ID");

    /**
     * The column <code>StockMarket.USMarketCompany.companyname</code>. 公司名称
     */
    public final TableField<UsmarketcompanyRecord, String> COMPANYNAME = createField("companyname", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "公司名称");

    /**
     * The column <code>StockMarket.USMarketCompany.currentprice</code>. Current stock price
     */
    public final TableField<UsmarketcompanyRecord, Double> CURRENTPRICE = createField("currentprice", org.jooq.impl.SQLDataType.DOUBLE, this, "Current stock price");

    /**
     * The column <code>StockMarket.USMarketCompany.currentpricetimestamp</code>.
     */
    public final TableField<UsmarketcompanyRecord, Timestamp> CURRENTPRICETIMESTAMP = createField("currentpricetimestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>StockMarket.USMarketCompany.openprice</code>. 开盘价
     */
    public final TableField<UsmarketcompanyRecord, Double> OPENPRICE = createField("openprice", org.jooq.impl.SQLDataType.DOUBLE, this, "开盘价");

    /**
     * The column <code>StockMarket.USMarketCompany.closeprice</code>. 昨日收盘价
     */
    public final TableField<UsmarketcompanyRecord, Double> CLOSEPRICE = createField("closeprice", org.jooq.impl.SQLDataType.DOUBLE, this, "昨日收盘价");

    /**
     * The column <code>StockMarket.USMarketCompany.highest_price</code>. 最高价
     */
    public final TableField<UsmarketcompanyRecord, Double> HIGHEST_PRICE = createField("highest_price", org.jooq.impl.SQLDataType.DOUBLE, this, "最高价");

    /**
     * The column <code>StockMarket.USMarketCompany.lowest_price</code>. 最低价
     */
    public final TableField<UsmarketcompanyRecord, Double> LOWEST_PRICE = createField("lowest_price", org.jooq.impl.SQLDataType.DOUBLE, this, "最低价");

    /**
     * The column <code>StockMarket.USMarketCompany.marketcap</code>. 总市值
     */
    public final TableField<UsmarketcompanyRecord, String> MARKETCAP = createField("marketcap", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "总市值");

    /**
     * The column <code>StockMarket.USMarketCompany.capitalizationvalue</code>. 流通市值
     */
    public final TableField<UsmarketcompanyRecord, String> CAPITALIZATIONVALUE = createField("capitalizationvalue", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "流通市值");

    /**
     * The column <code>StockMarket.USMarketCompany.tradingvolume</code>. 成交量
     */
    public final TableField<UsmarketcompanyRecord, String> TRADINGVOLUME = createField("tradingvolume", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "成交量");

    /**
     * The column <code>StockMarket.USMarketCompany.tradingvalue</code>. 成交额
     */
    public final TableField<UsmarketcompanyRecord, String> TRADINGVALUE = createField("tradingvalue", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "成交额");

    /**
     * The column <code>StockMarket.USMarketCompany.oscillation</code>. 股票振幅
     */
    public final TableField<UsmarketcompanyRecord, String> OSCILLATION = createField("oscillation", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "股票振幅");

    /**
     * The column <code>StockMarket.USMarketCompany.turnoverrate</code>. 换手率
     */
    public final TableField<UsmarketcompanyRecord, String> TURNOVERRATE = createField("turnoverrate", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "换手率");

    /**
     * The column <code>StockMarket.USMarketCompany.PBR</code>. 市净率 Price-to-book ratio
     */
    public final TableField<UsmarketcompanyRecord, Double> PBR = createField("PBR", org.jooq.impl.SQLDataType.DOUBLE.defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DOUBLE)), this, "市净率 Price-to-book ratio");

    /**
     * The column <code>StockMarket.USMarketCompany.PER</code>. 市盈率
     */
    public final TableField<UsmarketcompanyRecord, Double> PER = createField("PER", org.jooq.impl.SQLDataType.DOUBLE.defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DOUBLE)), this, "市盈率");

    /**
     * The column <code>StockMarket.USMarketCompany.last_update_date_time</code>. 最后一次更新时间
     */
    public final TableField<UsmarketcompanyRecord, Timestamp> LAST_UPDATE_DATE_TIME = createField("last_update_date_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "最后一次更新时间");

    /**
     * Create a <code>StockMarket.USMarketCompany</code> table reference
     */
    public Usmarketcompany() {
        this("USMarketCompany", null);
    }

    /**
     * Create an aliased <code>StockMarket.USMarketCompany</code> table reference
     */
    public Usmarketcompany(String alias) {
        this(alias, USMARKETCOMPANY);
    }

    private Usmarketcompany(String alias, Table<UsmarketcompanyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Usmarketcompany(String alias, Table<UsmarketcompanyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stockmarket.STOCKMARKET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UsmarketcompanyRecord> getPrimaryKey() {
        return Keys.KEY_USMARKETCOMPANY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UsmarketcompanyRecord>> getKeys() {
        return Arrays.<UniqueKey<UsmarketcompanyRecord>>asList(Keys.KEY_USMARKETCOMPANY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Usmarketcompany as(String alias) {
        return new Usmarketcompany(alias, this);
    }

    /**
     * Rename this table
     */
    public Usmarketcompany rename(String name) {
        return new Usmarketcompany(name, null);
    }
}
