/**
 * This class is generated by jOOQ
 */
package JooqORM.tables;


import JooqORM.Keys;
import JooqORM.Stockmarket;
import JooqORM.tables.records.UsmarketCompanyRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsmarketCompany extends TableImpl<UsmarketCompanyRecord> {

    private static final long serialVersionUID = 1883451866;

    /**
     * The reference instance of <code>StockMarket.usmarket_company</code>
     */
    public static final UsmarketCompany USMARKET_COMPANY = new UsmarketCompany();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsmarketCompanyRecord> getRecordType() {
        return UsmarketCompanyRecord.class;
    }

    /**
     * The column <code>StockMarket.usmarket_company.stockid</code>. 股票ID
     */
    public final TableField<UsmarketCompanyRecord, String> STOCKID = createField("stockid", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "股票ID");

    /**
     * The column <code>StockMarket.usmarket_company.capitalizationvalue</code>. 流通市值
     */
    public final TableField<UsmarketCompanyRecord, String> CAPITALIZATIONVALUE = createField("capitalizationvalue", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "流通市值");

    /**
     * The column <code>StockMarket.usmarket_company.close_price</code>. 昨日收盘价
     */
    public final TableField<UsmarketCompanyRecord, Double> CLOSE_PRICE = createField("close_price", org.jooq.impl.SQLDataType.DOUBLE, this, "昨日收盘价");

    /**
     * The column <code>StockMarket.usmarket_company.companyname</code>. 公司名称
     */
    public final TableField<UsmarketCompanyRecord, String> COMPANYNAME = createField("companyname", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "公司名称");

    /**
     * The column <code>StockMarket.usmarket_company.currentprice</code>. Current Price
     */
    public final TableField<UsmarketCompanyRecord, Double> CURRENTPRICE = createField("currentprice", org.jooq.impl.SQLDataType.DOUBLE, this, "Current Price");

    /**
     * The column <code>StockMarket.usmarket_company.currentpricetimestamp</code>.
     */
    public final TableField<UsmarketCompanyRecord, Timestamp> CURRENTPRICETIMESTAMP = createField("currentpricetimestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>StockMarket.usmarket_company.highest_price</code>. 最高价
     */
    public final TableField<UsmarketCompanyRecord, Double> HIGHEST_PRICE = createField("highest_price", org.jooq.impl.SQLDataType.DOUBLE, this, "最高价");

    /**
     * The column <code>StockMarket.usmarket_company.last_update_date_time</code>. 最后一次更新时间
     */
    public final TableField<UsmarketCompanyRecord, Timestamp> LAST_UPDATE_DATE_TIME = createField("last_update_date_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "最后一次更新时间");

    /**
     * The column <code>StockMarket.usmarket_company.lowest_price</code>. 最低价
     */
    public final TableField<UsmarketCompanyRecord, Double> LOWEST_PRICE = createField("lowest_price", org.jooq.impl.SQLDataType.DOUBLE, this, "最低价");

    /**
     * The column <code>StockMarket.usmarket_company.marketcap</code>. 总市值
     */
    public final TableField<UsmarketCompanyRecord, String> MARKETCAP = createField("marketcap", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "总市值");

    /**
     * The column <code>StockMarket.usmarket_company.openprice</code>. 开盘价
     */
    public final TableField<UsmarketCompanyRecord, Double> OPENPRICE = createField("openprice", org.jooq.impl.SQLDataType.DOUBLE, this, "开盘价");

    /**
     * The column <code>StockMarket.usmarket_company.oscillation</code>. 股票振幅
     */
    public final TableField<UsmarketCompanyRecord, String> OSCILLATION = createField("oscillation", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "股票振幅");

    /**
     * The column <code>StockMarket.usmarket_company.pbr</code>. 市净率 Price-to-book ratio
     */
    public final TableField<UsmarketCompanyRecord, Double> PBR = createField("pbr", org.jooq.impl.SQLDataType.DOUBLE, this, "市净率 Price-to-book ratio");

    /**
     * The column <code>StockMarket.usmarket_company.per</code>. 市盈率
     */
    public final TableField<UsmarketCompanyRecord, Double> PER = createField("per", org.jooq.impl.SQLDataType.DOUBLE, this, "市盈率");

    /**
     * The column <code>StockMarket.usmarket_company.tradingvalue</code>. 成交额
     */
    public final TableField<UsmarketCompanyRecord, String> TRADINGVALUE = createField("tradingvalue", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "成交额");

    /**
     * The column <code>StockMarket.usmarket_company.tradingvolume</code>. 成交量
     */
    public final TableField<UsmarketCompanyRecord, String> TRADINGVOLUME = createField("tradingvolume", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "成交量");

    /**
     * The column <code>StockMarket.usmarket_company.turnoverrate</code>. 换手率
     */
    public final TableField<UsmarketCompanyRecord, String> TURNOVERRATE = createField("turnoverrate", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "换手率");

    /**
     * The column <code>StockMarket.usmarket_company.listing_date</code>.
     */
    public final TableField<UsmarketCompanyRecord, Timestamp> LISTING_DATE = createField("listing_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>StockMarket.usmarket_company</code> table reference
     */
    public UsmarketCompany() {
        this("usmarket_company", null);
    }

    /**
     * Create an aliased <code>StockMarket.usmarket_company</code> table reference
     */
    public UsmarketCompany(String alias) {
        this(alias, USMARKET_COMPANY);
    }

    private UsmarketCompany(String alias, Table<UsmarketCompanyRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsmarketCompany(String alias, Table<UsmarketCompanyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stockmarket.STOCKMARKET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UsmarketCompanyRecord> getPrimaryKey() {
        return Keys.KEY_USMARKET_COMPANY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UsmarketCompanyRecord>> getKeys() {
        return Arrays.<UniqueKey<UsmarketCompanyRecord>>asList(Keys.KEY_USMARKET_COMPANY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsmarketCompany as(String alias) {
        return new UsmarketCompany(alias, this);
    }

    /**
     * Rename this table
     */
    public UsmarketCompany rename(String name) {
        return new UsmarketCompany(name, null);
    }
}
