/**
 * This class is generated by jOOQ
 */
package JooqORM.tables.records;


import JooqORM.tables.Chinesemarketcompany;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChinesemarketcompanyRecord extends UpdatableRecordImpl<ChinesemarketcompanyRecord> implements Record17<String, String, Double, Timestamp, Double, Double, Double, Double, String, String, String, String, String, String, Double, Double, Timestamp> {

    private static final long serialVersionUID = 2075487886;

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.stockid</code>. 股票ID
     */
    public void setStockid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.stockid</code>. 股票ID
     */
    public String getStockid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.companyname</code>. 公司名称
     */
    public void setCompanyname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.companyname</code>. 公司名称
     */
    public String getCompanyname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.currentprice</code>. Current stock price
     */
    public void setCurrentprice(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.currentprice</code>. Current stock price
     */
    public Double getCurrentprice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.currentpricetimestamp</code>.
     */
    public void setCurrentpricetimestamp(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.currentpricetimestamp</code>.
     */
    public Timestamp getCurrentpricetimestamp() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.openprice</code>. 开盘价
     */
    public void setOpenprice(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.openprice</code>. 开盘价
     */
    public Double getOpenprice() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.closeprice</code>. 昨日收盘价
     */
    public void setCloseprice(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.closeprice</code>. 昨日收盘价
     */
    public Double getCloseprice() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.highest_price</code>. 最高价
     */
    public void setHighestPrice(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.highest_price</code>. 最高价
     */
    public Double getHighestPrice() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.lowest_price</code>. 最低价
     */
    public void setLowestPrice(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.lowest_price</code>. 最低价
     */
    public Double getLowestPrice() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.marketcap</code>. 总市值
     */
    public void setMarketcap(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.marketcap</code>. 总市值
     */
    public String getMarketcap() {
        return (String) get(8);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.capitalizationvalue</code>. 流通市值
     */
    public void setCapitalizationvalue(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.capitalizationvalue</code>. 流通市值
     */
    public String getCapitalizationvalue() {
        return (String) get(9);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.tradingvolume</code>. 成交量
     */
    public void setTradingvolume(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.tradingvolume</code>. 成交量
     */
    public String getTradingvolume() {
        return (String) get(10);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.tradingvalue</code>. 成交额
     */
    public void setTradingvalue(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.tradingvalue</code>. 成交额
     */
    public String getTradingvalue() {
        return (String) get(11);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.oscillation</code>. 股票振幅
     */
    public void setOscillation(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.oscillation</code>. 股票振幅
     */
    public String getOscillation() {
        return (String) get(12);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.turnoverrate</code>. 换手率
     */
    public void setTurnoverrate(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.turnoverrate</code>. 换手率
     */
    public String getTurnoverrate() {
        return (String) get(13);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.PBR</code>. 市净率 Price-to-book ratio
     */
    public void setPbr(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.PBR</code>. 市净率 Price-to-book ratio
     */
    public Double getPbr() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.PER</code>. 市盈率
     */
    public void setPer(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.PER</code>. 市盈率
     */
    public Double getPer() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>StockMarket.ChineseMarketCompany.last_update_date_time</code>. 最后一次更新时间
     */
    public void setLastUpdateDateTime(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>StockMarket.ChineseMarketCompany.last_update_date_time</code>. 最后一次更新时间
     */
    public Timestamp getLastUpdateDateTime() {
        return (Timestamp) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, String, Double, Timestamp, Double, Double, Double, Double, String, String, String, String, String, String, Double, Double, Timestamp> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, String, Double, Timestamp, Double, Double, Double, Double, String, String, String, String, String, String, Double, Double, Timestamp> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.STOCKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.COMPANYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.CURRENTPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.CURRENTPRICETIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.OPENPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.CLOSEPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.HIGHEST_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.LOWEST_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.MARKETCAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.CAPITALIZATIONVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.TRADINGVOLUME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.TRADINGVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.OSCILLATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.TURNOVERRATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field15() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.PBR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field16() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.PER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return Chinesemarketcompany.CHINESEMARKETCOMPANY.LAST_UPDATE_DATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getStockid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCompanyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getCurrentprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCurrentpricetimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getOpenprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getCloseprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getHighestPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getLowestPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getMarketcap();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCapitalizationvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getTradingvolume();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTradingvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getOscillation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getTurnoverrate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value15() {
        return getPbr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value16() {
        return getPer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getLastUpdateDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value1(String value) {
        setStockid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value2(String value) {
        setCompanyname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value3(Double value) {
        setCurrentprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value4(Timestamp value) {
        setCurrentpricetimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value5(Double value) {
        setOpenprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value6(Double value) {
        setCloseprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value7(Double value) {
        setHighestPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value8(Double value) {
        setLowestPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value9(String value) {
        setMarketcap(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value10(String value) {
        setCapitalizationvalue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value11(String value) {
        setTradingvolume(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value12(String value) {
        setTradingvalue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value13(String value) {
        setOscillation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value14(String value) {
        setTurnoverrate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value15(Double value) {
        setPbr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value16(Double value) {
        setPer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord value17(Timestamp value) {
        setLastUpdateDateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChinesemarketcompanyRecord values(String value1, String value2, Double value3, Timestamp value4, Double value5, Double value6, Double value7, Double value8, String value9, String value10, String value11, String value12, String value13, String value14, Double value15, Double value16, Timestamp value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChinesemarketcompanyRecord
     */
    public ChinesemarketcompanyRecord() {
        super(Chinesemarketcompany.CHINESEMARKETCOMPANY);
    }

    /**
     * Create a detached, initialised ChinesemarketcompanyRecord
     */
    public ChinesemarketcompanyRecord(String stockid, String companyname, Double currentprice, Timestamp currentpricetimestamp, Double openprice, Double closeprice, Double highestPrice, Double lowestPrice, String marketcap, String capitalizationvalue, String tradingvolume, String tradingvalue, String oscillation, String turnoverrate, Double pbr, Double per, Timestamp lastUpdateDateTime) {
        super(Chinesemarketcompany.CHINESEMARKETCOMPANY);

        set(0, stockid);
        set(1, companyname);
        set(2, currentprice);
        set(3, currentpricetimestamp);
        set(4, openprice);
        set(5, closeprice);
        set(6, highestPrice);
        set(7, lowestPrice);
        set(8, marketcap);
        set(9, capitalizationvalue);
        set(10, tradingvolume);
        set(11, tradingvalue);
        set(12, oscillation);
        set(13, turnoverrate);
        set(14, pbr);
        set(15, per);
        set(16, lastUpdateDateTime);
    }
}
