/**
 * This class is generated by jOOQ
 */
package JooqORM.tables.records;


import JooqORM.tables.Cmarketearning;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmarketearningRecord extends UpdatableRecordImpl<CmarketearningRecord> implements Record4<String, Double, String, Double> {

    private static final long serialVersionUID = 1010413429;

    /**
     * Setter for <code>StockMarket.cmarketearning.stockid</code>. 股票ID
     */
    public void setStockid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>StockMarket.cmarketearning.stockid</code>. 股票ID
     */
    public String getStockid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>StockMarket.cmarketearning.grossmargin</code>. 毛利率
     */
    public void setGrossmargin(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>StockMarket.cmarketearning.grossmargin</code>. 毛利率
     */
    public Double getGrossmargin() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>StockMarket.cmarketearning.reporturl</code>. 主要财务指标
     */
    public void setReporturl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>StockMarket.cmarketearning.reporturl</code>. 主要财务指标
     */
    public String getReporturl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>StockMarket.cmarketearning.roe</code>. 净资产收益率
     */
    public void setRoe(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>StockMarket.cmarketearning.roe</code>. 净资产收益率
     */
    public Double getRoe() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Double, String, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Double, String, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Cmarketearning.CMARKETEARNING.STOCKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field2() {
        return Cmarketearning.CMARKETEARNING.GROSSMARGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Cmarketearning.CMARKETEARNING.REPORTURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Cmarketearning.CMARKETEARNING.ROE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getStockid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value2() {
        return getGrossmargin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getReporturl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getRoe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmarketearningRecord value1(String value) {
        setStockid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmarketearningRecord value2(Double value) {
        setGrossmargin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmarketearningRecord value3(String value) {
        setReporturl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmarketearningRecord value4(Double value) {
        setRoe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmarketearningRecord values(String value1, Double value2, String value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CmarketearningRecord
     */
    public CmarketearningRecord() {
        super(Cmarketearning.CMARKETEARNING);
    }

    /**
     * Create a detached, initialised CmarketearningRecord
     */
    public CmarketearningRecord(String stockid, Double grossmargin, String reporturl, Double roe) {
        super(Cmarketearning.CMARKETEARNING);

        set(0, stockid);
        set(1, grossmargin);
        set(2, reporturl);
        set(3, roe);
    }
}
