/**
 * This class is generated by jOOQ
 */
package JooqORM;


import JooqORM.tables.Company;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chinesestock extends SchemaImpl {

    private static final long serialVersionUID = 715590074;

    /**
     * The reference instance of <code>ChineseStock</code>
     */
    public static final Chinesestock CHINESESTOCK = new Chinesestock();

    /**
     * The table <code>ChineseStock.Company</code>.
     */
    public final Company COMPANY = JooqORM.tables.Company.COMPANY;

    /**
     * No further instances allowed
     */
    private Chinesestock() {
        super("ChineseStock", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Company.COMPANY);
    }
}
